### ISSUE TITLE
How many figures should I put in?

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [maudzung/Complex-YOLOv4-Pytorch#10]
I tried
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 128 --num_workers 0...
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 128 --num_workers 1...
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 128 --num_workers 16...

but train.py: error: argument --num_workers: invalid int value: '0...' this error occur
train.py: error: argument --num_workers: invalid int value: '1...' this error occur
train.py: error: argument --num_workers: invalid int value: '16...' this error occur

**Comment by maudzung** [comment]
Hi @Jihun-Kim-kmu 
Please refer the _'train.sh'_ script to see how to train the model. You need to remove _..._.

**Comment by Jihun-Kim-kmu** [comment]
I didn't know the script file was present. Thank you for your advice.
