### ISSUE TITLE
AssertionError: scalar should be 0D

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [maudzung/Complex-YOLOv4-Pytorch#11]
I've put the figures by referring to the train.sh file.
![image](https://user-images.githubusercontent.com/65701965/88534489-29268d00-d043-11ea-8b56-078194866fb6.png)
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 4 --num_workers 4
and this error occur
![image](https://user-images.githubusercontent.com/65701965/88534576-54a97780-d043-11ea-9d4d-e65a6f207966.png)
It seems to be a dimension problem in the np, is there any py file that needs to be modified?

**Comment by maudzung** [comment]
You should check out the latest code.
`git pull`
