### ISSUE TITLE
opencv-python version problem

### ISSUE THREAD

**Issue by wxchencn** [maudzung/Complex-YOLOv4-Pytorch#12]
I found a strange problem, using the latest version of `opencv-python-4.3.0.36` will cause `segmentation fault`. I located the problem in `kitti_dataloader.py` at line 164 `cv2.imshow()`.

env: 
> Ubuntu 18.04; Python3.6

output:
> [1]    21406 segmentation fault (core dumped)  python kitti_dataloader.py --output-width 608

If someone has the same problem,  you can uninstall `opencv-python` and execute `pip install opencv-python==4.2.0.34`.
Thanks for the excellent work！

**Comment by maudzung** [comment]
Thanks for reporting the error. 
I have already listed the dependent libraries in the `requirement.txt` file.

```
torch==1.5.0
torchvision==0.6.0
easydict==1.9
opencv-python==4.2.0.34
numpy==1.18.3
torchsummary==1.5.1
tensorboard==2.2.1
scikit-learn==0.22.2
```
