### ISSUE TITLE
Can I use it to train more classes?

### ISSUE THREAD

**Issue by CNWindson** [maudzung/Complex-YOLOv4-Pytorch#14]
@maudzung 
Here's a question that I want to train with net with more classes.(There is a task I should give the result with car,pedestrian,cyclist and truck) Can it works? Could you plz give me some advice?Thanks a lot and forgive me for my bad English.

**Comment by maudzung** [comment]
Hi @CNWindson 

Of course, you can train the model with more classes. You should change:
1. The number of filters in the YOLO layer.
In the cfg file, let's change the line [#965](https://github.com/maudzung/Complex-YOLOv4-Pytorch/blob/d50e2d55c4aae6df5595cf2835a10731c0ff742f/src/config/cfg/complex_yolov4.cfg#L961), [#1050](https://github.com/maudzung/Complex-YOLOv4-Pytorch/blob/d50e2d55c4aae6df5595cf2835a10731c0ff742f/src/config/cfg/complex_yolov4.cfg#L1050), [#1139](https://github.com/maudzung/Complex-YOLOv4-Pytorch/blob/d50e2d55c4aae6df5595cf2835a10731c0ff742f/src/config/cfg/complex_yolov4.cfg#L1139)
The `#filters = 3 * (7 + num_classes)`

2. Add more classes' id to [here](https://github.com/maudzung/Complex-YOLOv4-Pytorch/blob/d50e2d55c4aae6df5595cf2835a10731c0ff742f/src/config/kitti_config.py#L5)

**Comment by CNWindson** [comment]
@maudzung 
It's my honour to get your reply! Thanks a lot. I will try.

**Comment by maudzung** [comment]
You are welcome. Let's try and let me know if you have any problems. I'll try to help you as much as I can!

**Comment by CNWindson** [comment]
@maudzung 
How kind you are and sorry to bother you again. Shoud I make some change in any scripts to get the eval result ?  I have tried to do the same thing in the [Complex-yolo-v3](https://github.com/ghimiredhikura/Complex-YOLOv3#complex-yolo-v3). But I only got three eval result (Pedestrian,Cyclist and car).
