### ISSUE TITLE
pre-train model 

### ISSUE THREAD

**Issue by abhigoku10** [maudzung/Complex-YOLOv4-Pytorch#3]
@maudzung  can you share the pre-trained model ??

**Comment by maudzung** [comment]
Hi @abhigoku10 

I'm running more experiments to choose the best model for the task. Please stay tuned and watch the repo, I'll release the trained model soon. Thanks!

**Comment by maudzung** [comment]
@abhigoku10 You can play with the pre-trained **_Complex-YOLOv3_** model first. I have already provided the link and instructions in the `README.md` file.

Link: [**_pre-trained Complex-YOLOv3_** model](https://drive.google.com/file/d/1gEpVxfgJZ9CTDt1ym2W0M5OHDjdCZzAw/view)

**Comment by abhigoku10** [comment]
@maudzung  sure will wait for it , yup i have played with complexyolov3 also

**Comment by maudzung** [comment]
Have fun coding! :-)
