### ISSUE TITLE
Evaluate the model on test dataset

### ISSUE THREAD

**Issue by bhaskar-anand-iith** [maudzung/Complex-YOLOv4-Pytorch#47]
I believe that currently evaluate.py evaluates the model on validation data.
How to evaluate on test dataset?

**Comment by bhaskar-anand-iith** [comment]
My mistake. We can do inference, not evaluation on test dataset as labels are not available.

**Comment by Petros626** [comment]
@bhaskar-anand-iith Did you get metrics with difficulties?
