### ISSUE TITLE
How to show outputs in forms other than BEV?

### ISSUE THREAD

**Issue by tanay-o** [maudzung/Complex-YOLOv4-Pytorch#58]
I have been trying to find references to plot 3D boxes on the pointcloud data in forms other than BEV.

Any leads for the same?

**Comment by vjsrinivas** [comment]
If you save your output in the same way this project does: https://github.com/NVIDIA-AI-IOT/CUDA-PointPillars
You can generate visualization with this other project very easily: https://github.com/kuixu/kitti_object_vis

**Comment by tanay-o** [comment]
Yes, I was able to get the desired results with this, thank you so much.
