### ISSUE TITLE
I want to know the development environment.

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [maudzung/Complex-YOLOv4-Pytorch#6]
Thank you for sharing the source
I want to know your development environment. ubuntu, cuda, cudnn etc..
Can you tell me the program versions i need to run the program?
Are you use anaconda environment?

**Comment by maudzung** [comment]
Hi @Jihun-Kim-kmu 

My environment:
- Ubuntu 18.04
- CUDA: 10.2
- cuDNN: 7.6.5
- Python: 3.6
- PyTorch: 1.5

I'm not using Anaconda. The source code is running in a virtual environment. For more information, you can refer to my notes for the installation of the virtual environment [here](https://github.com/maudzung/virtual_environment_python3)

**Comment by Jihun-Kim-kmu** [comment]
Thank you for your answer. Can I ask you again if I have an error later?

**Comment by maudzung** [comment]
Ok, sure @Jihun-Kim-kmu 
Let's develop the repo. I'm also running more experiments to improve the performance of models.
