### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Darknet:

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [maudzung/Complex-YOLOv4-Pytorch#8]
I succeeded in step 2.4.1.
![image](https://user-images.githubusercontent.com/65701965/88362260-ca4ce380-cdb6-11ea-85e6-4fdd7c055008.png)

I'm currently working on step 2.4.2.
2.4.2. Inference
python test.py --gpu_idx 0 --pretrained_path <PATH>...

In this step I think pretrained_path means complex_yolov3.pth so I made file and  put complex_yolov3.pth 
![image](https://user-images.githubusercontent.com/65701965/88362354-316a9800-cdb7-11ea-938b-c89f0a3b1a96.png)

And run python test.py --gpu_idx 0 --pretrained_path /home/kaai/Complex-YOLOv4-Pytorch/ab/complex_yolov3.pth

![image](https://user-images.githubusercontent.com/65701965/88362413-6119a000-cdb7-11ea-8c6e-e8d8e5b30184.png)
![image](https://user-images.githubusercontent.com/65701965/88362416-65de5400-cdb7-11ea-8617-64bbe8e77760.png)

Is there anything wrong with my progress?

**Comment by maudzung** [comment]
Hi @Jihun-Kim-kmu 
Let's try:
`python test.py --gpu_idx 0 --pretrained_path /home/kaai/Complex-YOLOv4-Pytorch/ab/complex_yolov3.pth --cfgfile ./config/cfg/complex_yolov3.cfg`

**Comment by Jihun-Kim-kmu** [comment]
Thank you for your prompt reply. you're right
It's going on normally now. thank you
![image](https://user-images.githubusercontent.com/65701965/88363407-ece0fb80-cdba-11ea-8743-7e8bd51af684.png)

**Comment by maudzung** [comment]
You are welcome.
I'm trying to improve the performance of the Complex-YOLOv4 model. I'll release the pre-trained model when it works well.
Let's develop it!
