### ISSUE TITLE
What are the differences between single machines and tow machines?

### ISSUE THREAD

**Issue by Jihun-Kim-kmu** [maudzung/Complex-YOLOv4-Pytorch#9]
I am currently working on this. 
Single machine (node), multiple GPUs
$ python train.py --dist-url 'tcp://127.0.0.1:29500' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0
I use a titian RTX. Is it right use this code? What are the differences between single machines and tow machines?
![image](https://user-images.githubusercontent.com/65701965/88368870-d9895c80-cdc9-11ea-89e0-e1578aa16067.png)

......................................................................................................

![image](https://user-images.githubusercontent.com/65701965/88371467-0c821f00-cdcf-11ea-92cf-45b8b5156257.png)
this error occur.....
Do i have to use single gpu?

**Comment by maudzung** [comment]
Hi @Jihun-Kim-kmu 
You have a single GPU, so you should follow the instruction for [training on a single machine, single gpu (2.4.4.1)](https://github.com/maudzung/Complex-YOLOv4-Pytorch#2441-single-machine-single-gpu)
You can read more [here](https://pytorch.org/tutorials/intermediate/dist_tuto.html)

**Comment by Jihun-Kim-kmu** [comment]
this step How many figures should I put in?
I tried
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 128 --num_workers 0...
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 128 --num_workers 1...
$ python train.py --gpu_idx 0 --multiscale_training --batch_size 128 --num_workers 16...

but train.py: error: argument --num_workers: invalid int value: '0...' this error occur
